# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
