# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quiz_taken',
            field=models.IntegerField(default=0),
        ),
    ]
